<program> ::= {<declaration>}
<declaration> ::= <variable-declaration> | <function-declaration>
<variable-declaration> ::= {<specifier>}+ <identifier> ["=" <exp>] ";"
<function-declaration> ::= {<specifier>}+ <identifier> "(" <paramlist> ")" (<block> | ";")
<param-list> ::= "void" | "int" <identifier> {"," "int" <identifier>}
<specifier> ::= "static" | "extern" | "int"
<block> ::= "{" {<block-item} "}"
<block-item> ::= <statement> | <declaration>
<statement> ::= "return" <exp> ";"
                | <labeled-statement>
                | "goto" <identifier> ";"
                | "if" "(" <exp> ")" <statement> ["else" <statement>]
                | <block>
                | break ";"
                | continue ";"
                | "while" "(" <exp> ")" <statement>
                | "do" <statement> "while" "(" <exp> ")" ";"
                | "for" "(" <for-init> [<exp>] ";" [<exp>] ")" <statement>
                | "switch" "(" <exp> ")" <statement>
                | <exp> ";"
                | ";"
<labeled-statement> ::= <identifier> ":" <statement> | "case" <expr> ":" <statement | "default" ":" <statement>
<for-init> ::= <variable-declaration> | [<exp>] ";"
<exp> ::= <factor> | <exp> <binop> <exp> | <exp> "?" <exp> ":" <exp>
<factor> ::= <unop> <factor> | <postfix>
<postfix> ::= <primary> { <postfix-op> }
<primary> ::= <int> | <identifier> | "(" <exp> ")" | <identifier> "(" [<argument-list>] ")"
<argument-list> ::= <exp> {"," <exp>}
<unop> ::= "-" | "~" | "!" | "--" | "++"
<postfix-op> ::= "--" | "++"
<binop> ::= "-" | "+" | "*" | "/" | "%" | "&" | "|" | "^" | "<<" | ">>" | "&&" | "||" | "==" | "!=" | "<" | "<=" | ">" | ">="
<identifier> ::= ? An identifier token ?
<int> ::= ? A constant token ?