<program> ::= <function>
<function> ::= "int" <identifier> "(" "void" ")" <block>
<block> ::= "{" {<block-item} "}"
<block-item> ::= <statement> | <declaration>
<declaration> ::= "int" <identifier> ["=" <exp>] ";"
<statement> ::= "return" <exp> ";"
                | <labeled-statement>
                | "goto" <identifier> ";"
                | "if" "(" <exp> ")" <statement> ["else" <statement>]
                | <block>
                | break ";"
                | continue ";"
                | "while" "(" <exp> ")" <statement>
                | "do" <statement> "while" "(" <exp> ")" ";"
                | "for" "(" <for-init> [<exp>] ";" [<exp>] ")" <statement>
                | "switch" "(" <exp> ")" <statement>
                | <exp> ";"
                | ";"
<labeled-statement> ::= <identifier> ":" <statement> | "case" <expr> ":" <statement | "default" ":" <statement>
<for-init> ::= <declaration> | [<exp>] ";"
<exp> ::= <factor> | <exp> <binop> <exp> | <exp> "?" <exp> ":" <exp>
<factor> ::= <unop> <factor> | <postfix>
<postfix> ::= <primary> { <postfix-op> }
<primary> ::= <int> | <identifier> | "(" <exp> ")"
<unop> ::= "-" | "~" | "!" | "--" | "++"
<postfix-op> ::= "--" | "++"
<binop> ::= "-" | "+" | "*" | "/" | "%" | "&" | "|" | "^" | "<<" | ">>" | "&&" | "||" | "==" | "!=" | "<" | "<=" | ">" | ">="
<identifier> ::= ? An identifier token ?
<int> ::= ? A constant token ?